# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-158076145-1
gauges_analytics:
favicon: /favicon.png
twitter: "komesunchu"
ogp_image: themes/komesu.jpeg
google_plus:
fb_admins:
fb_app_id:
open_graph:
    twitter_id: '@komesunchu'
    twitter_site:  '@komesunchu'
    desription: 'As You Like'
    twitter_card: 'summary'
